"use client";

import dynamic from "next/dynamic";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import PageBreadCrumb from "@/components/common/PageBreadCrumb";
import { api } from "@/lib/api-client";
import { useTheme } from "@/context/ThemeContext";

const Chart = dynamic(() => import("react-apexcharts"), { ssr: false });
type Analytics = { summary: { total: number; new: number; progressed: number; converted: number; conversionRate: number }; monthly: { month: string; leads: number; converted: number }[]; channels: { name: string; leads: number; converted: number; conversionRate: number }[]; statuses: { status: string; count: number }[]; campaigns: { name: string; leads: number; contacted: number; converted: number; conversionRate: number }[] };
const label = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

export default function LeadAnalyticsPage() {
  const { theme } = useTheme();
  const isDark = theme === "dark";
  const now = new Date();
  const [data, setData] = useState<Analytics | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [year, setYear] = useState(now.getFullYear()); const [month, setMonth] = useState<number | "all">("all"); const [source, setSource] = useState("all");
  const years = Array.from({ length: 5 }, (_, index) => now.getFullYear() - index);
  const periodLabel = month === "all" ? `All months in ${year}` : `${MONTHS[month - 1]} ${year}`;
  const load = useCallback(async () => { setLoading(true); const params = new URLSearchParams(); const startMonth = month === "all" ? 0 : month - 1; const endMonth = month === "all" ? 11 : month - 1; const from = `${year}-${String(startMonth + 1).padStart(2, "0")}-01`; const lastDay = new Date(year, endMonth + 1, 0).getDate(); const to = `${year}-${String(endMonth + 1).padStart(2, "0")}-${lastDay}`; params.set("from", from); params.set("to", to); if (source !== "all") params.set("source", source); const res = await api.get<{ success: boolean; data: Analytics }>(`/api/leads/analytics?${params}`); if (res.error) setError(res.error.message); else { setError(""); setData(res.data?.data || null); } setLoading(false); }, [year, month, source]);
  useEffect(() => { load(); }, [load]);
  const chartText = isDark ? "#cbd5e1" : "#64748b";
  const chartGrid = isDark ? "#334155" : "#e2e8f0";
  const axis = { labels: { style: { colors: chartText } }, axisBorder: { color: chartGrid }, axisTicks: { color: chartGrid } };
  const chartTheme = { mode: (isDark ? "dark" : "light") as "dark" | "light" };
  return <div className="space-y-6"><PageBreadCrumb pageTitle="Lead Analytics" />
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-2xl font-bold text-gray-900 dark:text-white">Lead Analytics</h1><p className="mt-1 text-sm text-gray-500">Month-to-month progress, channel performance and conversion outcomes.</p><div className="mt-2 inline-flex rounded-full bg-violet-50 px-3 py-1 text-xs font-bold text-violet-700 dark:bg-violet-950/30 dark:text-violet-300">Reporting period: {periodLabel}</div></div><Link href="/leads" className="rounded-lg border border-gray-200 px-4 py-2 text-sm font-semibold">← Back to Leads CRM</Link></div>
    <div className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-700 dark:bg-gray-800"><div className="mb-4"><h2 className="font-bold text-gray-900 dark:text-white">Report filters</h2><p className="text-sm text-gray-500">Choose a month or review the full year.</p></div><div className="grid gap-3 sm:grid-cols-4"><label><span className="mb-1 block text-xs font-bold uppercase text-gray-400">Month</span><select value={month} onChange={(e) => setMonth(e.target.value === "all" ? "all" : Number(e.target.value))} className="w-full rounded-lg border px-3 py-2.5 dark:bg-gray-700"><option value="all">All months</option>{MONTHS.map((name, index) => <option key={name} value={index + 1}>{name}</option>)}</select></label><label><span className="mb-1 block text-xs font-bold uppercase text-gray-400">Year</span><select value={year} onChange={(e) => setYear(Number(e.target.value))} className="w-full rounded-lg border px-3 py-2.5 dark:bg-gray-700">{years.map((item) => <option key={item}>{item}</option>)}</select></label><label><span className="mb-1 block text-xs font-bold uppercase text-gray-400">Channel</span><select value={source} onChange={(e) => setSource(e.target.value)} className="w-full rounded-lg border px-3 py-2.5 dark:bg-gray-700"><option value="all">All channels</option>{["Meta", "TikTok", "Website", "Manual", "Other"].map((item) => <option key={item}>{item}</option>)}</select></label><button onClick={() => { setMonth("all"); setYear(now.getFullYear()); setSource("all"); }} className="self-end rounded-lg border px-4 py-2.5 font-semibold">Reset filters</button></div></div>
    {error && <div className="rounded-xl bg-red-50 p-4 text-red-700">{error}</div>}{loading ? <div className="p-16 text-center text-gray-500">Loading analytics…</div> : data && <>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[["Total leads", data.summary.total], ["New / untouched", data.summary.new], ["Progressed", data.summary.progressed], ["Converted", data.summary.converted], ["Conversion rate", `${data.summary.conversionRate}%`]].map(([name, value]) => <div key={name} className="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-700 dark:bg-gray-800"><div className="text-xs font-bold uppercase text-gray-400">{name}</div><div className="mt-2 text-3xl font-bold">{value}</div></div>)}</div>
      <div className="grid gap-6 xl:grid-cols-2"><section className="rounded-2xl border border-gray-200 bg-white p-6 dark:border-gray-700 dark:bg-gray-800"><h2 className="text-lg font-bold text-gray-900 dark:text-white">Month-to-month leads</h2><p className="text-sm text-gray-500 dark:text-gray-400">New volume compared with conversions</p><Chart type="bar" height={330} series={[{ name: "Leads", data: data.monthly.map((item) => item.leads) }, { name: "Converted", data: data.monthly.map((item) => item.converted) }]} options={{ theme: chartTheme, chart: { toolbar: { show: false }, background: "transparent", foreColor: chartText }, grid: { borderColor: chartGrid }, tooltip: { theme: isDark ? "dark" : "light" }, colors: ["#6366f1", "#10b981"], plotOptions: { bar: { borderRadius: 5, columnWidth: "48%" } }, xaxis: { ...axis, categories: data.monthly.map((item) => item.month) }, yaxis: axis, dataLabels: { enabled: false }, legend: { position: "top", labels: { colors: chartText } } }} /></section>
      <section className="rounded-2xl border border-gray-200 bg-white p-6 dark:border-gray-700 dark:bg-gray-800"><h2 className="text-lg font-bold text-gray-900 dark:text-white">Leads by channel</h2><p className="text-sm text-gray-500 dark:text-gray-400">Where your leads originate</p><Chart type="donut" height={330} series={data.channels.map((item) => item.leads)} options={{ theme: chartTheme, chart: { background: "transparent", foreColor: chartText }, tooltip: { theme: isDark ? "dark" : "light" }, labels: data.channels.map((item) => item.name), colors: ["#6366f1", "#ec4899", "#06b6d4", "#f59e0b", "#94a3b8"], stroke: { colors: [isDark ? "#1f2937" : "#ffffff"] }, legend: { position: "bottom", labels: { colors: chartText } }, dataLabels: { enabled: true } }} /></section></div>
      <div className="grid gap-6 xl:grid-cols-2"><section className="rounded-2xl border border-gray-200 bg-white p-6 dark:border-gray-700 dark:bg-gray-800"><h2 className="text-lg font-bold text-gray-900 dark:text-white">Pipeline status</h2><p className="text-sm text-gray-500 dark:text-gray-400">Current lead outcomes across the funnel</p><Chart type="bar" height={360} series={[{ name: "Leads", data: data.statuses.map((item) => item.count) }]} options={{ theme: chartTheme, chart: { toolbar: { show: false }, background: "transparent", foreColor: chartText }, grid: { borderColor: chartGrid }, tooltip: { theme: isDark ? "dark" : "light" }, colors: ["#8b5cf6"], plotOptions: { bar: { horizontal: true, borderRadius: 4 } }, xaxis: { ...axis, categories: data.statuses.map((item) => label(item.status)) }, yaxis: axis, dataLabels: { enabled: true, style: { colors: ["#ffffff"] } } }} /></section>
      <section className="overflow-hidden rounded-2xl border bg-white dark:border-gray-700 dark:bg-gray-800"><div className="p-6"><h2 className="text-lg font-bold">Channel performance</h2><p className="text-sm text-gray-500">Volume and conversion effectiveness</p></div><table className="w-full text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500 dark:bg-gray-900/40"><tr><th className="px-5 py-3 text-left">Channel</th><th className="px-5 py-3 text-right">Leads</th><th className="px-5 py-3 text-right">Converted</th><th className="px-5 py-3 text-right">Rate</th></tr></thead><tbody className="divide-y dark:divide-gray-700">{data.channels.map((item) => <tr key={item.name}><td className="px-5 py-4 font-semibold">{item.name}</td><td className="px-5 py-4 text-right">{item.leads}</td><td className="px-5 py-4 text-right">{item.converted}</td><td className="px-5 py-4 text-right font-semibold text-emerald-600">{item.conversionRate}%</td></tr>)}</tbody></table></section></div>
      <section className="overflow-hidden rounded-2xl border bg-white dark:border-gray-700 dark:bg-gray-800"><div className="p-6"><h2 className="text-lg font-bold">Campaign performance</h2><p className="text-sm text-gray-500">Compare lead volume, progress and results</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500 dark:bg-gray-900/40"><tr><th className="px-6 py-3 text-left">Campaign</th><th className="px-6 py-3 text-right">Leads</th><th className="px-6 py-3 text-right">Progressed</th><th className="px-6 py-3 text-right">Converted</th><th className="px-6 py-3 text-right">Conversion</th></tr></thead><tbody className="divide-y dark:divide-gray-700">{data.campaigns.map((item) => <tr key={item.name}><td className="px-6 py-4 font-semibold">{item.name}</td><td className="px-6 py-4 text-right">{item.leads}</td><td className="px-6 py-4 text-right">{item.contacted}</td><td className="px-6 py-4 text-right">{item.converted}</td><td className="px-6 py-4 text-right font-semibold">{item.conversionRate}%</td></tr>)}</tbody></table></div></section>
    </>}</div>;
}
